version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver"


    environment:
      - DB_HOST=db
      - DB_PORTS=5432
      - DB_NAME=uppi
      - DB_USER=debug
      - DB_PASS=debug
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=debug
      - POSTGRES_PASSWORD=debug
      - POSTGRES_DB=uppi
    ports:
      - 5432:5432
volumes:
  dev-db-data: